export const TreatmentConditionOptions = [
  { id: 'TT', label: 'Tit Tar (TT)' },
  { id: 'MG', label: 'Massage Gun (MG)' },
  { id: 'CG', label: 'Chiro Gun (CG)' },
  { id: 'CT', label: 'Zhen Dao (CT)' },
  { id: 'MT', label: 'Magnetik (MT)' },
  { id: 'CUP', label: 'Cupping (CUP)' },
  { id: 'DN', label: 'Dry Needling (DN)' },
  { id: 'BKM', label: 'Bekam (BKM)' },
  { id: 'BB', label: 'Bebatu (BB)' },
  { id: 'GH', label: 'Ghuasa (GH)' },
  { id: 'KT', label: 'Kursi Terapi (KT)' },
  { id: 'BSM', label: 'Body Space Medicine (BSM)' },
  { id: 'TDP', label: 'Teding Diancibo Pu / Infrared (TDP)' },
  { id: 'PL', label: 'Palu (PL)' },
]
